import type { WorkspaceItem } from './types'

type ReferenceItem = Omit<WorkspaceItem, 'id' | 'createdAt' | 'updatedAt'> & { importKey: string }
const s = { menu: 'Menu & Operations Guide v3', equipment: 'Equipment, Packaging & Procurement Guide v3', checklist: 'Launch Checklist v3', business: 'Business Plan v3', costing: 'Cost workbooks v3', notes: 'Boba Bear planning notes' }

export const referenceCatalog: ReferenceItem[] = [
  { importKey: 'note-brand-open', title: 'Brand identity is still open', body: 'Boba Bear is the active working brand. The final logo and visual system are not yet selected.', kind: 'Note', section: 'Notes', area: 'General', source: s.notes },
  { importKey: 'note-location-open', title: 'Store location is not finalized', body: 'The business is prelaunch. Candidate areas need visits, rent quotes, frontage checks, utilities checks, and student footfall validation.', kind: 'Note', section: 'Notes', area: 'General', source: s.notes },
  { importKey: 'note-menu-validation', title: 'Opening-board menu needs tasting', body: 'The planning menu is a reference list. Samples, recipe trials, supplier reliability, labels, MOQ, and cost must be checked before selecting Day 1 flavors.', kind: 'Note', section: 'Notes', area: 'General', source: s.menu },
  { importKey: 'note-no-fixed-budget', title: 'Record real quotes and purchases', body: 'Do not treat old funding or budget assumptions as fixed. Add current quotes, purchases, and expenses as they happen.', kind: 'Note', section: 'Notes', area: 'General', source: s.notes },

  { importKey: 'menu-milk-tea', title: 'Flavored Milk Tea — planning range', body: 'Matcha; Mango / Alphonso; Strawberry; Butterscotch; Papaya; Honeydew; Pina Colada; Coffee Mocha; Blueberry; Chocolate; Taro. Planning price: ₹149 small / ₹199 regular. Each flavor still needs tasting and costing.', kind: 'Drink', section: 'Menu', area: 'Milk Tea', status: 'Testing', details: { category: 'Milk tea', flavors: 'Matcha; Mango / Alphonso; Strawberry; Butterscotch; Papaya; Honeydew; Pina Colada; Coffee Mocha; Blueberry; Chocolate; Taro', planningPriceSmall: '149', planningPriceRegular: '199', launchPhase: 'Opening menu' }, source: s.menu },
  { importKey: 'menu-fruit-tea', title: 'Fruit Tea — planning range', body: 'Honeydew; Orange / Kumquat; Dragon Fruit; Mango; Passion Fruit; Strawberry. Planning price: ₹149 small / ₹199 regular. Syrup sourcing remains open.', kind: 'Drink', section: 'Menu', area: 'Fruit Tea', status: 'Testing', details: { category: 'Fruit tea', flavors: 'Honeydew; Orange / Kumquat; Dragon Fruit; Mango; Passion Fruit; Strawberry', planningPriceSmall: '149', planningPriceRegular: '199', launchPhase: 'Opening menu' }, source: s.menu },
  { importKey: 'menu-lassi', title: 'Boba Lassi — planning range', body: 'Plain; Pistachio; Banana; Rose; Mango. One-size planning price: ₹129. Recipes and supplied flavors need testing.', kind: 'Drink', section: 'Menu', area: 'Boba Lassi', status: 'Testing', details: { category: 'Boba lassi', flavors: 'Plain; Pistachio; Banana; Rose; Mango', planningPriceRegular: '129', launchPhase: 'Opening menu' }, source: s.menu },
  { importKey: 'menu-tapioca', title: 'Tapioca toppings', body: 'Black tapioca pearls and Tutti Frutti tapioca pearls. Planning add-on: ₹30. Validate cook time, texture, holding time, and yield.', kind: 'Drink', section: 'Menu', area: 'Toppings', status: 'Testing', details: { category: 'Toppings', flavors: 'Black tapioca pearls; Tutti Frutti tapioca pearls', planningPriceRegular: '30', launchPhase: 'Opening menu' }, source: s.menu },
  { importKey: 'menu-jelly', title: 'Jelly toppings', body: 'Strawberry, Pineapple, and Lychee jelly. Planning add-on: ₹30. Validate flavor, cut size, shelf life, and label details.', kind: 'Drink', section: 'Menu', area: 'Toppings', status: 'Testing', details: { category: 'Toppings', flavors: 'Strawberry jelly; Pineapple jelly; Lychee jelly', planningPriceRegular: '30', launchPhase: 'Opening menu' }, source: s.menu },
  { importKey: 'menu-popping', title: 'Popping boba toppings', body: 'Lychee, Black Currant, Mango, Blueberry, and Strawberry. Planning add-on: ₹30. Test each sample before selection.', kind: 'Drink', section: 'Menu', area: 'Toppings', status: 'Testing', details: { category: 'Toppings', flavors: 'Lychee; Black Currant; Mango; Blueberry; Strawberry', planningPriceRegular: '30', launchPhase: 'Opening menu' }, source: s.menu },
  { importKey: 'menu-phase-two', title: 'Phase 2 drinks', body: 'Fruit Blends and Milk Blends were intentionally deferred until real demand is known.', kind: 'Drink', section: 'Menu', area: 'Preparation', status: 'Researching', details: { category: 'Phase 2 drinks', flavors: 'Fruit Blends; Milk Blends', launchPhase: 'Phase 2' }, source: s.menu },

  { importKey: 'supplier-tea-planet', title: 'The Tea Planet', body: 'Primary sample candidate because Hyderabad is closer to Khammam. Ask for samples, MOQ, delivered cost, shelf life, label/FSSAI details, and lead time.', kind: 'Supplier', section: 'Suppliers', area: 'Tea Planet', url: 'https://theteaplanet.com/', status: 'Researching', details: { location: 'Hyderabad', categories: 'Popping boba, tapioca, milk-tea powders, lassi flavors, equipment' }, source: s.menu },
  { importKey: 'supplier-qqs', title: 'QQS Bubble Tea', body: 'Candidate for Mango / Alphonso, Strawberry, Butterscotch, Papaya, and Honeydew powders. Verify seller, labels, samples, MOQ, and reliability.', kind: 'Supplier', section: 'Suppliers', area: 'QQS Bubble Tea', url: 'https://www.indiamart.com/qqsbubbletea/', status: 'Researching', details: { location: 'New Delhi', categories: 'Milk-tea powders' }, source: s.menu },
  { importKey: 'supplier-zawaa', title: 'Zawaa Foods', body: 'Candidate for Matcha powder and Strawberry, Pineapple, and Lychee jellies. Request samples and current commercial details.', kind: 'Supplier', section: 'Suppliers', area: 'Zawaa Foods', url: 'https://zawaafoods.com/', status: 'Researching', details: { categories: 'Matcha powder, fruit jellies' }, source: s.menu },
  { importKey: 'supplier-local', title: 'Local Khammam sourcing', body: 'Find dependable local sources for black tea, green tea, milk, fresh curd/yogurt, sugar, ice, water, cleaning supplies, and routine consumables.', kind: 'Supplier', section: 'Suppliers', area: 'Local Khammam', status: 'Researching', details: { location: 'Khammam', categories: 'Tea, milk, curd, sugar, ice, consumables' }, source: s.menu },

  { importKey: 'setup-locations', title: 'Current location search areas', body: 'Look near Ibaco, Zudio, and Unlimited; also Kaviraj Nagar, Varadiah Nagar, Rotary Nagar, and Mamatha Hospital Road. Add each property separately after a visit.', kind: 'Note', section: 'Store Setup', area: 'Locations', source: s.notes },
  { importKey: 'setup-sealer', title: '95 mm cup sealing machine', body: 'Prefer a machine compatible with a common 95 mm rim. Confirm cup and film compatibility using actual samples before buying.', kind: 'Note', section: 'Store Setup', area: 'Equipment', source: s.equipment },
  { importKey: 'setup-blender', title: 'Commercial blender plus backup', body: 'Reference need: 1.5–2 L commercial blender with a practical backup. Validate service availability, jar replacements, noise, and throughput.', kind: 'Note', section: 'Store Setup', area: 'Equipment', source: s.equipment },
  { importKey: 'setup-tools', title: 'Shakers and measuring tools', body: 'Plan shaker cups, jiggers, measuring cups, scales, scoops, thermometers, timers, strainers, and labeled containers.', kind: 'Note', section: 'Store Setup', area: 'Equipment', source: s.equipment },
  { importKey: 'setup-brewing', title: 'Tea brewing stations', body: 'Compare induction-based brewing and commercial tea brewers. Plan two stations so tea and tapioca work do not block each other.', kind: 'Note', section: 'Store Setup', area: 'Equipment', source: s.equipment },
  { importKey: 'setup-tapioca', title: 'Tapioca cooking and holding station', body: 'Plan cooking pot, induction unit, strainer, timer, holding container, and cleaning workflow. A specialized cooker can wait.', kind: 'Note', section: 'Store Setup', area: 'Equipment', source: s.equipment },
  { importKey: 'setup-cold', title: 'Refrigerator and freezer', body: 'Reference need: approximately 250–300 L cooler and 100–160 L freezer. Final capacity depends on the store and supply frequency.', kind: 'Note', section: 'Store Setup', area: 'Equipment', source: s.equipment },
  { importKey: 'setup-water', title: 'RO water system', body: 'Commercial RO sizing depends on source-water quality and daily demand. Test local water and verify service support.', kind: 'Note', section: 'Store Setup', area: 'Equipment', source: s.equipment },
  { importKey: 'setup-steel', title: 'Sinks, worktables, handwash, and shelving', body: 'Plan stainless worktables, wash sink, dedicated handwash, drain access, and easy-clean storage. Final layout depends on the property.', kind: 'Note', section: 'Store Setup', area: 'Equipment', source: s.equipment },
  { importKey: 'setup-pos', title: 'POS, tablet, printer, and connectivity', body: 'A movable tablet-based POS is preferred. Compare receipt/label printing, UPI, online orders, router, CCTV, and UPS.', kind: 'Note', section: 'Store Setup', area: 'Equipment', source: s.notes },
  { importKey: 'setup-safety', title: 'Safety and sanitation equipment', body: 'Include fire safety, first aid, food-safe cleaning tools, sanitizer, waste bins, pest control, and staff hygiene supplies.', kind: 'Note', section: 'Store Setup', area: 'Equipment', source: s.equipment },
  { importKey: 'packaging-direction', title: 'Kraft carrier packaging direction', body: 'Preferred for takeaway and delivery: Kraft paper carrier with a built-in handle. Compare one-cup and two-cup fit, strength, condensation resistance, and price.', kind: 'Link', section: 'Store Setup', area: 'Packaging', url: 'https://store.yenchuan.co/products/packaging/carriers/craft-paper-cup-carrier-2-cups/', source: s.notes },
  { importKey: 'packaging-one-cup', title: 'One-cup Kraft carrier reference', body: 'Visual and construction reference only; supplier and exact design are not selected.', kind: 'Link', section: 'Store Setup', area: 'Packaging', url: 'https://store.yenchuan.co/products/packaging/carriers/craft-paper-cup-carrier-1-cup/', source: s.notes },
  { importKey: 'packaging-holder', title: 'Alternative cup-holder reference', body: 'Compare its structure and delivery stability with the Kraft handle-carrier direction.', kind: 'Link', section: 'Store Setup', area: 'Packaging', url: 'https://cafepack.com.tr/en/products/cup-holder', source: s.notes },
  { importKey: 'packaging-core', title: 'Launch packaging system', body: 'Start with two sealable paper cup sizes, wide paper straws, molded-pulp carriers, paper bags, and plain cups with stickers. Custom printed cups can wait.', kind: 'Note', section: 'Store Setup', area: 'Packaging', source: s.equipment },
  { importKey: 'workflow-order', title: 'Draft counter-to-drink workflow', body: 'Cashier confirms the order and payment, details reach the drink maker, the drink is prepared and checked, then called by name or order number. Label/receipt method needs POS testing.', kind: 'Note', section: 'Store Setup', area: 'Store Workflow', source: s.notes },
  { importKey: 'workflow-delivery', title: 'Draft online-delivery workflow', body: 'Delivery orders should be prepared, sealed, packed, and handed over through the cashier side. Final process depends on platforms and store layout.', kind: 'Note', section: 'Store Setup', area: 'Store Workflow', source: s.notes },
  { importKey: 'checklist-reference', title: 'Launch checklist — all phases open', body: 'The old checklist covers planning, location/legal, procurement, menu trials, hiring/training, soft launch, and opening. Review every task against the current plan.', kind: 'Note', section: 'Store Setup', area: 'Legal', source: s.checklist },

  { importKey: 'marketing-influencers', title: 'Influencer outreach tracker', body: 'Add each person contacted separately with Instagram link, contact date, response, quoted cost, deliverables, and next step. No spend is recorded yet.', kind: 'Note', section: 'Marketing', area: 'Influencers', source: s.notes },
  { importKey: 'marketing-prelaunch', title: 'Prelaunch information stays private', body: 'Full menu and location are not announced. Public updates should wait until the opening menu and location are ready.', kind: 'Note', section: 'Marketing', area: 'Instagram', source: s.notes },
  { importKey: 'money-live-records', title: 'Use current quotes, purchases, and expenses', body: 'Old workbook amounts are planning references, not an approved budget. Add quotes and purchases individually so totals come from actual records.', kind: 'Note', section: 'Money', area: 'Estimate', source: s.costing },

  { importKey: 'library-menu-guide', title: 'Menu & Operations Guide v3', body: 'Historical planning reference. Review before treating any detail as current.', kind: 'File', section: 'Library', area: 'Document', url: 'Boba_Bear_Menu_Operations_Guide_v3(3).docx', source: s.menu },
  { importKey: 'library-launch-checklist', title: 'Launch Checklist v3', body: 'Historical launch workplan. All statuses need current review.', kind: 'File', section: 'Library', area: 'Document', url: 'Boba_Bear_Launch_Checklist_v3(3).docx', source: s.checklist },
  { importKey: 'library-equipment-guide', title: 'Equipment & Packaging Guide v3', body: 'Reference for procurement categories, packaging compatibility, and equipment research.', kind: 'File', section: 'Library', area: 'Document', url: 'Boba_Bear_Equipment_Packaging_Procurement_Guide_v3(3).docx', source: s.equipment },
  { importKey: 'library-business-plan', title: 'Business Plan v3', body: 'Historical concept and assumptions. Location, funding, staffing, and projections are not current commitments.', kind: 'File', section: 'Library', area: 'Document', url: 'Boba_Bear_Business_Plan_v3(3).docx', source: s.business },
  { importKey: 'library-cost-drink', title: 'Cost Per Drink workbook v3', body: 'Replace assumptions with tested recipes and current delivered ingredient costs.', kind: 'File', section: 'Library', area: 'Spreadsheet', url: 'Boba_Bear_Cost_Per_Drink_v3(3).xlsx', source: s.costing },
  { importKey: 'library-cost-breakdown', title: 'Costs Breakdown workbook v3', body: 'Historical startup and operating-cost model. Do not use as a fixed budget.', kind: 'File', section: 'Library', area: 'Spreadsheet', url: 'Boba_Bear_Costs_Breakdown_v3(3).xlsx', source: s.costing },
  { importKey: 'library-order-flow', title: 'Ordering Flow v3', body: 'Reference ordering-flow concept. Final POS and counter workflow still require testing.', kind: 'File', section: 'Library', area: 'Document', url: 'Boba_Bear_Ordering_Flow_v3(3).html', source: s.notes },
  { importKey: 'library-readme', title: 'Boba Bear v3 package read-me', body: 'Source-package notes and file overview.', kind: 'File', section: 'Library', area: 'Document', url: 'Boba_Bear_v3_Package_Read_Me(3).txt', source: s.notes },
]
